### ISSUE TITLE
Dalvikvm is way slow on Android 12

### ISSUE THREAD

**Issue by hanyman7** [termux/termux-tools#15] opened 2022-09-04 19:12 UTC
When running a simple .dex hello world it takes about 3.8 seconds.

The default of -Xnoimage-dex2oat on pre Android 12 has changed to  -Ximage-dex2oat.

So a lot of time is taken to precompile dex files and all jar dependencies to a binary ELF as though it is a full APK :-( only to be deleted since it is not required to be persisted via other dalvikvm option. This is all done prior to calling main.

This script needs to be updated to specify -Xnoimage-dex2oat as a default

**Comment by agnostic-apollo** [comment] 2022-09-05 11:04
Duplicate of termux/termux-app#2967

**Closed by agnostic-apollo** 2022-09-05 11:04 UTC
